---
- hosts: Raspberry_Pi
  become: yes
  vars_files:
    - "{{ lookup('env', 'HOME') }}/Ansible-H.IAAC/vault.yml"

  tasks:
    - name: Garantir que o diretório do cliente exista no Pi
      file:
        # Caminho explícito para a home do usuário 'pi'
        path: /home/pi/flower_client
        state: directory
        # Define 'pi' como o dono, para evitar problemas de permissão
        owner: pi
        group: pi
        mode: '0755'

    - name: Copiar o arquivo client.py para os Pis
      copy:
        # Origem no seu laptop
        src: "{{ lookup('env', 'HOME') }}/TESTBED/client.py"
        # Destino explícito na home do usuário 'pi'
        dest: /home/pi/flower_client/client.py
        # Define 'pi' como o dono do arquivo
        owner: pi
        group: pi
        mode: '0644'