---
- hosts: Raspberry_Pi
  become: yes
  vars_files:
    - "{{ lookup('env', 'HOME') }}/Ansible-H.IAAC/vault.yml"
  
  tasks:
    - name: Garantir que o diretório do cliente exista no Pi
      file:
        path: "{{ ansible_env.HOME }}/flower_client"
        state: directory
        # É uma boa prática definir o dono para evitar problemas de permissão
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'

    - name: Copiar o arquivo client.py para os Pis
      copy:
        # CORREÇÃO: Aponta para a pasta TESTBED no seu laptop
        src: "{{ lookup('env', 'HOME') }}/TESTBED/client.py"
        
        # O destino no Pi continua o mesmo
        dest: "{{ ansible_env.HOME }}/flower_client/client.py"
        
        # Define o dono do arquivo como o usuário do Pi
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'