---
- hosts: Raspberry_Pi
  become: yes # Necessário para os comandos 'apt' e para corrigir permissões
  vars_files:
    - "{{ lookup('env', 'HOME') }}/Ansible-H.IAAC/vault.yml"

  tasks:
    - name: Garantir dependências do sistema (Python e Pip)
      apt:
        name:
          - python3.11
          - python3.11-venv
          - python3-pip
        state: present
        update_cache: yes

    - name: Criar o diretório para os ambientes virtuais
      file:
        path: /home/pi/venvs
        state: directory
        owner: pi
        group: pi
        mode: '0755'

    - name: Criar o ambiente virtual 'myenv'
      command:
        cmd: "python3.11 -m venv /home/pi/venvs/myenv"
        creates: /home/pi/venvs/myenv/bin/activate
      become: no # Executa como 'pi'

    # --- TAREFA DE CORREÇÃO ADICIONADA AQUI ---
    - name: Garantir que o usuário 'pi' seja o dono do diretório do venv
      file:
        path: /home/pi/venvs/myenv
        state: directory
        owner: pi
        group: pi
        recurse: yes # Aplica a permissão a todos os arquivos e subpastas
      # 'become: yes' é herdado do topo, o que é necessário aqui para mudar o dono de 'root' para 'pi'

    - name: Instalar flwr e tensorflow (tarefa de longa duração)
      pip:
        name:
          - flwr
          - tensorflow
        virtualenv: /home/pi/venvs/myenv
      become: no # Executa como 'pi'
      async: 1800
      poll: 15