---
- hosts: Raspberry_Pi
  become: yes # Necessário para os comandos 'apt'
  vars_files:
    - "{{ lookup('env', 'HOME') }}/Ansible-H.IAAC/vault.yml"

  tasks:
    - name: Garantir dependências do sistema (Python e Pip)
      apt:
        name:
          - python3.11
          - python3.11-venv
          - python3-pip
        state: present
        update_cache: yes

    - name: Criar o diretório para os ambientes virtuais
      file:
        path: /home/pi/venvs
        state: directory
        owner: pi
        group: pi
        mode: '0755'

    - name: Criar o ambiente virtual 'myenv'
      command:
        cmd: "python3.11 -m venv /home/pi/venvs/myenv"
        creates: /home/pi/venvs/myenv/bin/activate
      become: no # Executa este comando como o usuário 'pi', não como 'root'

    - name: Instalar flwr e tensorflow (tarefa de longa duração)
      pip:
        name:
          - flwr
          - tensorflow
        virtualenv: /home/pi/venvs/myenv
      become: no # Executa o pip como o usuário 'pi'
      
      # CORREÇÃO: Dá até 30 minutos (1800s) para a tarefa completar
      async: 1800
      # E verifica o status a cada 15 segundos
      poll: 15