---
- hosts: Raspberry_Pi  # Roda o Playbook em todas as Pis
  become: yes
  vars_files:
    - "{{ lookup('env', 'HOME') }}/Ansible-H.IAAC/vault.yml"

  tasks:
    - name: Verificar se o Python 3.11 está instalado
      command: python3.11 --version
      register: python_version
      ignore_errors: yes  # Não falha se o Python não estiver instalado

    - name: Instalar Python 3.11 caso não esteja presente
      apt:
        name: python3.11
        state: present
      when: python_version.rc != 0

    - name: Garantir que o pip esteja instalado
      apt:
        name: python3-pip
        state: present

    - name: Criar o ambiente virtual em /home/pi/venvs/myenv
      command:
        cmd: python3.11 -m venv /home/pi/venvs/myenv
        creates: "/home/pi/venvs/myenv"  # Cria o venv apenas se ele não existir

    - name: Instalar pacotes necessários no venv
      pip:
        name: requests  # exemplo de pacote
        virtualenv: /home/pi/venvs/myenv  # Instalar no ambiente virtual
