---
- hosts:
    - Raspberry_Pi
    - Jetsons
  become: no
  vars_files:
    - "{{ lookup('env', 'HOME') }}/Ansible-H.IAAC/vault.yml"

  tasks:
    - name: Iniciar o script do cliente Flower em modo assíncrono
      shell:
        # CHAMADA DIRETA: Usamos o caminho completo para o Python do venv
        cmd: "nohup /home/pi/venvs/myenv/bin/python client.py > /home/pi/flower_client/client.log 2>&1 &"
        
        chdir: /home/pi/flower_client
      
      async: 10
      poll: 0