---
- hosts:
    - Raspberry_Pi
    - Jetsons
  become: yes
  vars_files:
    - "{{ lookup('env', 'HOME') }}/Ansible-H.IAAC/vault.yml"

  tasks:

    # --- ETAPA 1: Lógica para descobrir dinamicamente o usuário, home e GRUPO ---
    - name: Descobrir o home directory real do usuário de conexão
      shell: "getent passwd {{ ansible_user }} | cut -d: -f6"
      register: user_home_dir_output
      changed_when: false
      become: no

    - name: Descobrir o grupo primário real do usuário de conexão
      shell: "id -gn {{ ansible_user }}" # <-- NOVA TAREFA ADICIONADA
      register: user_group_output
      changed_when: false
      become: no

    - name: Definir variáveis de fato com os caminhos e grupos corretos
      set_fact:
        correct_user_home: "{{ user_home_dir_output.stdout }}"
        correct_user_group: "{{ user_group_output.stdout }}"



    - name: Garantir que o diretório do cliente exista no Pi
      file:
        path: "{{ correct_user_home }}/FilesTestbed/flower_client"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ correct_user_group }}" # <-- CORRIGIDO
        mode: '0755'

    - name: Copiar o arquivo client.py para os Pis
      copy:
        # Origem no server
        src: "{{ lookup('env', 'HOME') }}/TESTBED/client.py"
        dest: "{{ correct_user_home }}/FilesTestbed/flower_client/client.py"
        owner: "{{ ansible_user }}"
        group: "{{ correct_user_group }}" # <-- CORRIGIDO
        mode: '0755'