---
- hosts:
    - Raspberry_Pi
    - Jetsons
  become: yes
  vars_files:
    - "{{ lookup('env', 'HOME') }}/Ansible-H.IAAC/vault.yml"

  tasks:
    # --- ETAPA 1: Lógica para descobrir dinamicamente o usuário, home e GRUPO ---
    - name: Descobrir o home directory real do usuário de conexão
      shell: "getent passwd {{ ansible_user }} | cut -d: -f6"
      register: user_home_dir_output
      changed_when: false
      become: no

    - name: Descobrir o grupo primário real do usuário de conexão
      shell: "id -gn {{ ansible_user }}" # <-- NOVA TAREFA ADICIONADA
      register: user_group_output
      changed_when: false
      become: no

    - name: Definir variáveis de fato com os caminhos e grupos corretos
      set_fact:
        correct_user_home: "{{ user_home_dir_output.stdout }}"
        correct_user_group: "{{ user_group_output.stdout }}" # <-- NOVA VARIÁVEL

    # --- ETAPA 2: O restante do playbook agora usa as variáveis dinâmicas ---
    - name: Garantir dependências do sistema (Python e Pip)
      apt:
        name:
          - python3.11
          - python3.11-venv
          - python3-pip
        state: present
        update_cache: yes

    - name: Criar o diretório para os ambientes virtuais
      file:
        path: "{{ correct_user_home }}/FilesTestbed/venvs"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ correct_user_group }}" # <-- CORRIGIDO
        mode: '0755'

    - name: Criar o ambiente virtual 'myenv'
      command:
        cmd: "python3.11 -m venv {{ correct_user_home }}/FilesTestbed/venvs/myenv"
        creates: "{{ correct_user_home }}/FilesTestbed/venvs/myenv/bin/activate"
      become: no

    - name: Garantir que o usuário de conexão seja o dono do diretório do venv
      file:
        path: "{{ correct_user_home }}/FilesTestbed/venvs/myenv"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ correct_user_group }}" # <-- CORRIGIDO
        recurse: yes

    - name: Instalar requirements (tarefa de longa duração)
      pip:
        name: "{{ lookup('file', lookup ('env', 'HOME') + '/TESTBED/requirements.txt') | splitlines }}"
        virtualenv: "{{ correct_user_home }}/FilesTestbed/venvs/myenv"
      become: no
      async: 1800
      poll: 15